function registerMap = define_register_map(exportFile, printSummary)
% create the initial register map

if nargin < 1 || isempty(exportFile)
    matlabDir = fileparts(mfilename('fullpath'));
    projectRoot = fileparts(fileparts(matlabDir));
    exportFile = fullfile(projectRoot, '05_INTEGRATION', 'Register_Map.csv');
end
if nargin < 2
    printSummary = true;
end

Address = { ...
    'HR001'; 'HR002'; 'HR003'; 'HR004'; 'HR005'; 'HR006'; 'HR007'; 'HR008'; 'HR009'; ...
    'HR101'; 'HR102'; 'HR103'; 'HR104'; 'HR105'; 'HR106'; ...
    'HR201'; 'HR202'; 'HR203'; 'HR204'; ...
    'HR301'; 'HR302'; 'HR303'; 'HR304'; 'HR305'; ...
    'C001'; 'C002'; 'C003'; 'C004'; 'C005'; 'C006'; 'C007'; 'C008'; ...
    'C051'; 'C052'; 'C053'; 'C054'; 'C055'; 'C056'; 'C057'; ...
    'C101'; 'C102'; 'C103'; 'C104'; 'C105'; ...
    'C251'; 'C252'; 'C253'; 'C254'};

Tag = { ...
    'LIT101_PV'; 'LIT201_PV'; 'LIT301_PV'; 'FIT101_PV'; 'FIT201_PV'; 'FIT301_PV'; ...
    'AIT201_PV'; 'PIT301_PV'; 'Plant_Heartbeat'; ...
    'P101A_SpeedCmd'; 'P101B_SpeedCmd'; 'P201_SpeedCmd'; 'P301A_SpeedCmd'; ...
    'P301B_SpeedCmd'; 'DP201_Output'; ...
    'Pressure_SP'; 'Concentration_SP'; 'BatchFill_SP'; 'MixTime_SP'; ...
    'Batch_State'; 'Batch_Count'; 'Rejected_Batch_Count'; 'Pressure_PI_Output'; ...
    'Concentration_PI_Output'; ...
    'P101A_RunFb'; 'P101B_RunFb'; 'P201_RunFb'; 'P301A_RunFb'; 'P301B_RunFb'; ...
    'M201_RunFb'; 'XV201_OpenFb'; 'XV201_ClosedFb'; ...
    'P101A_StartCmd'; 'P101B_StartCmd'; 'P201_StartCmd'; 'P301A_StartCmd'; ...
    'P301B_StartCmd'; 'M201_StartCmd'; 'XV201_OpenCmd'; ...
    'System_StartReq'; 'System_StopReq'; 'System_ResetReq'; 'Auto_ModeReq'; ...
    'Manual_ModeReq'; 'Fault_P301A_Trip'; 'Fault_AIT201_Freeze'; ...
    'Fault_XV201_StuckClosed'; 'Fault_CommsLoss'};

Direction = [ ...
    repmat({'Simulink_to_PLC'}, 9, 1); ...
    repmat({'PLC_to_Simulink'}, 6, 1); ...
    repmat({'Ignition_to_PLC'}, 4, 1); ...
    repmat({'PLC_to_Ignition'}, 5, 1); ...
    repmat({'Simulink_to_PLC'}, 8, 1); ...
    repmat({'PLC_to_Simulink'}, 7, 1); ...
    repmat({'Ignition_to_PLC'}, 5, 1); ...
    repmat({'Test_to_Simulink'}, 4, 1)];

DataType = [repmat({'UINT16'}, 24, 1); repmat({'BOOL'}, 24, 1)];
Scaling = [ ...
    {'% x10'; '% x10'; '% x10'; 'L/s x10'; 'L/s x10'; 'L/s x10'; ...
    'mg/L x100'; 'kPa x10'; 'count'; ...
    '% x10'; '% x10'; '% x10'; '% x10'; '% x10'; '% x10'; ...
    'kPa x10'; 'mg/L x100'; '% x10'; 's'; ...
    'integer'; 'integer'; 'integer'; '% x10'; '% x10'}; ...
    repmat({'Boolean'}, 24, 1)];

Units = [ ...
    {'%'; '%'; '%'; 'L/s'; 'L/s'; 'L/s'; 'mg/L'; 'kPa'; 'count'; ...
    '%'; '%'; '%'; '%'; '%'; '%'; 'kPa'; 'mg/L'; '%'; 's'; ...
    'state'; 'count'; 'count'; '%'; '%'}; ...
    repmat({'bool'}, 24, 1)];

Description = { ...
    'Raw-water tank level'; 'Treatment-tank level'; 'Clean-water tank level'; ...
    'Raw transfer flow'; 'Treatment transfer flow'; 'Distribution demand'; ...
    'Treatment concentration'; 'Distribution pressure'; 'Incrementing plant heartbeat'; ...
    'P-101A speed command'; 'P-101B speed command'; 'P-201 speed command'; ...
    'P-301A speed command'; 'P-301B speed command'; 'Dosing output'; ...
    'Pressure setpoint'; 'Concentration setpoint'; 'Treatment fill target'; 'Mixing time'; ...
    'Active batch state'; 'Completed batches'; 'Rejected batches'; ...
    'Total booster demand'; 'Dosing controller output'; ...
    'P-101A running feedback'; 'P-101B running feedback'; 'P-201 running feedback'; ...
    'P-301A running feedback'; 'P-301B running feedback'; 'Mixer running feedback'; ...
    'Treatment outlet valve open feedback'; 'Treatment outlet valve closed feedback'; ...
    'P-101A start command'; 'P-101B start command'; 'P-201 start command'; ...
    'P-301A start command'; 'P-301B start command'; 'Mixer start command'; ...
    'Treatment outlet valve open command'; 'Automatic system start request'; ...
    'System stop request'; 'System reset request'; 'Automatic-mode request'; ...
    'Manual-mode request'; 'Lead booster trip injection'; ...
    'Concentration sensor freeze injection'; 'Outlet valve stuck-closed injection'; ...
    'Communication-loss injection'};

registerMap = table(Address, Tag, Direction, DataType, Scaling, Units, Description);

if numel(unique(registerMap.Address)) ~= height(registerMap)
    error('WaterProject:DuplicateAddress', 'Duplicate register addresses detected.');
end
if numel(unique(registerMap.Tag)) ~= height(registerMap)
    error('WaterProject:DuplicateTag', 'Duplicate register-map tag names detected.');
end

exportDir = fileparts(exportFile);
if ~exist(exportDir, 'dir')
    mkdir(exportDir);
end
writetable(registerMap, exportFile);

if printSummary
    fprintf('\nRegister map created: %d tags\n', height(registerMap));
    fprintf('Exported to: %s\n', exportFile);
end
end
