function modelFile = build_openplc_integrated_model(forceRebuild)
%BUILD_OPENPLC_INTEGRATED_MODEL Generate the closed-loop Simulink/OpenPLC model.
%
% build_openplc_integrated_model(true) rebuilds the integrated model from
% the validated standalone Water_Treatment_Plant model.
%
% The generated model uses OpenPLCModbusBridge in Normal simulation mode.
% Simulink owns the physical plant and OpenPLC owns all operational control.

if nargin < 1
    forceRebuild = false;
end

check_openplc_requirements();

matlabDir = fileparts(mfilename('fullpath'));
projectRoot = fileparts(fileparts(matlabDir));
modelDir = fullfile(projectRoot, '02_SIMULINK');
baseName = 'Water_Treatment_Plant';
modelName = 'Water_Treatment_Plant_OpenPLC_v0_4';
baseFile = fullfile(modelDir, [baseName '.slx']);
modelFile = fullfile(modelDir, [modelName '.slx']);

if evalin('base', 'exist(''P'', ''var'')') == 0
    assignin('base', 'P', initialize_water_plant(false));
end
create_default_inputs(180, true);

if ~exist(baseFile, 'file')
    build_water_treatment_plant(true);
end

if exist(modelFile, 'file') && ~forceRebuild
    try
        load_system(modelFile);
        validate_openplc_integrated_model(modelName, true);
        open_system(modelName);
        fprintf('Opened existing integrated model: %s\n', modelFile);
        return;
    catch ME
        localCloseModel(modelName);
        warning( ...
            'WaterProject:RebuildingIntegratedModel', ...
            ['The existing integrated model is incomplete or from an older ' ...
             'revision and will be rebuilt. %s'], ...
            ME.message);
    end
end

localCloseModel(modelName);
localCloseModel(baseName);
copyfile(baseFile, modelFile, 'f');
load_system(modelFile);

% Remove standalone actuator command sources. Disturbances and equipment
% availability profiles remain From Workspace signals.
commandSources = { ...
    'cmd_P101A', 'cmd_P101B', 'cmd_P201', ...
    'cmd_P301A', 'cmd_P301B', 'cmd_DP201', ...
    'cmd_M201', 'cmd_XV201'};
for k = 1:numel(commandSources)
    localDeleteBlock([modelName '/' commandSources{k}]);
end

% Remove feedback terminators; their source signals are connected to the
% communication feedback vector below.
feedbackTerminators = { ...
    'Term_P101A_RunFb', 'Term_P101B_RunFb', ...
    'Term_P201_RunFb', ...
    'Term_P301A_RunFb', ...
    'Term_P301B_RunFb', ...
    'Term_XV201_OpenFb', 'Term_XV201_ClosedFb'};
for k = 1:numel(feedbackTerminators)
    localDeleteBlock([modelName '/' feedbackTerminators{k}]);
end

% Plant measurements sent to HR1-HR8.
add_block('simulink/Signal Routing/Mux', ...
    [modelName '/OpenPLC_Measurements'], ...
    'Inputs', '8', ...
    'Position', [1990 80 1995 305]);

measurementSources = { ...
    'Tank_T101/2', ...
    'Tank_T201/2', ...
    'Tank_T301/2', ...
    'P101_TotalFlow/1', ...
    'P201_ValveFlow/1', ...
    'DeliveredDemand/1', ...
    'Treatment_Concentration/2', ...
    'Distribution_Pressure/2'};
for k = 1:numel(measurementSources)
    add_line(modelName, measurementSources{k}, ...
        sprintf('OpenPLC_Measurements/%d', k), 'autorouting', 'on');
end

% Physical feedback sent to C1-C5 and C7-C8. Mixer feedback C6 is mirrored
% from the PLC mixer command inside OpenPLCModbusBridge.
add_block('simulink/Signal Routing/Mux', ...
    [modelName '/OpenPLC_Feedback'], ...
    'Inputs', '7', ...
    'Position', [1990 360 1995 555]);

feedbackSources = { ...
    'P101A_Actuator/3', ...
    'P101B_Actuator/3', ...
    'P201_Actuator/3', ...
    'P301A_Actuator/3', ...
    'P301B_Actuator/3', ...
    'XV201_Valve/2', ...
    'XV201_Valve/3'};
for k = 1:numel(feedbackSources)
    add_line(modelName, feedbackSources{k}, ...
        sprintf('OpenPLC_Feedback/%d', k), 'autorouting', 'on');
end

localAddCommunicationSubsystem(modelName);
add_line(modelName, 'OpenPLC_Measurements/1', ...
    'OpenPLC_Communication/1', 'autorouting', 'on');
add_line(modelName, 'OpenPLC_Feedback/1', ...
    'OpenPLC_Communication/2', 'autorouting', 'on');

% Split the bridge vectors so the actuator conditioning remains explicit.
add_block('simulink/Signal Routing/Demux', ...
    [modelName '/OpenPLC_Analog_Demux'], ...
    'Outputs', '6', ...
    'Position', [2475 70 2480 235]);
add_block('simulink/Signal Routing/Demux', ...
    [modelName '/OpenPLC_Digital_Demux'], ...
    'Outputs', '7', ...
    'Position', [2475 285 2480 480]);
add_block('simulink/Signal Routing/Demux', ...
    [modelName '/OpenPLC_Fault_Demux'], ...
    'Outputs', '4', ...
    'Position', [2475 535 2480 650]);

add_line(modelName, 'OpenPLC_Communication/1', ...
    'OpenPLC_Analog_Demux/1', 'autorouting', 'on');
add_line(modelName, 'OpenPLC_Communication/2', ...
    'OpenPLC_Digital_Demux/1', 'autorouting', 'on');
add_line(modelName, 'OpenPLC_Communication/3', ...
    'OpenPLC_Fault_Demux/1', 'autorouting', 'on');

localAddCommandTags(modelName);
localAddConditionedActuatorCommands(modelName);
localAddIntegrationLogging(modelName);

% Normal mode and wall-clock pacing are required because OpenPLC timers use
% real time while Simulink otherwise runs faster than real time.
set_param(modelName, ...
    'SimulationMode', 'normal', ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'ode4', ...
    'FixedStep', 'P.sim.baseStep_s', ...
    'StopTime', 'P.sim.defaultStopTime_s');
try
    set_param(modelName, 'EnablePacing', 'on', 'PacingRate', '1');
catch
    warning( ...
        'WaterProject:SimulationPacing', ...
        ['The model was built, but pacing could not be enabled by script. ' ...
         'Enable Simulation Pacing at 1x before running the model.']);
end

Simulink.Annotation(modelName, ...
    ['OpenPLC closed-loop integration: HR1-HR8 and C1-C8 are plant ' ...
     'feedback; HR101-HR106 and C51-C57 are PLC-owned commands; ' ...
     'HR301-HR317 and C151-C181 are logged diagnostics.']);

save_system(modelName, modelFile);
validate_openplc_integrated_model(modelName, true);
open_system(modelName);
fprintf('Generated integrated model: %s\n', modelFile);
end


function localAddCommunicationSubsystem(modelName)
path = [modelName '/OpenPLC_Communication'];
add_block('simulink/Ports & Subsystems/Subsystem', path, ...
    'Position', [2115 170 2385 430]);
Simulink.SubSystem.deleteContents(path);

add_block('simulink/Ports & Subsystems/In1', [path '/Measurements'], ...
    'Port', '1', 'Position', [25 75 55 95]);
add_block('simulink/Ports & Subsystems/In1', [path '/Feedback'], ...
    'Port', '2', 'Position', [25 155 55 175]);
add_block('simulink/User-Defined Functions/MATLAB System', ...
    [path '/OpenPLCModbusBridge'], ...
    'System', 'OpenPLCModbusBridge', ...
    'Position', [105 65 285 190]);

% Do not set the block's SimulateUsing mask parameter here. The System
% object declares interpreted execution through getSimulateUsingImpl, which
% makes SimulateUsing read-only in MATLAB R2026a. The generated block still
% reports "Interpreted execution", and the structural validator checks it.
add_block('simulink/Ports & Subsystems/Out1', [path '/AnalogCmd'], ...
    'Port', '1', 'Position', [345 55 375 75]);
add_block('simulink/Ports & Subsystems/Out1', [path '/DigitalCmd'], ...
    'Port', '2', 'Position', [345 100 375 120]);
add_block('simulink/Ports & Subsystems/Out1', [path '/Faults'], ...
    'Port', '3', 'Position', [345 145 375 165]);
add_block('simulink/Ports & Subsystems/Out1', [path '/CommHealthy'], ...
    'Port', '4', 'Position', [345 190 375 210]);
add_block('simulink/Ports & Subsystems/Out1', [path '/Diagnostics'], ...
    'Port', '5', 'Position', [345 235 375 255]);

add_line(path, 'Measurements/1', 'OpenPLCModbusBridge/1');
add_line(path, 'Feedback/1', 'OpenPLCModbusBridge/2');
add_line(path, 'OpenPLCModbusBridge/1', 'AnalogCmd/1');
add_line(path, 'OpenPLCModbusBridge/2', 'DigitalCmd/1');
add_line(path, 'OpenPLCModbusBridge/3', 'Faults/1');
add_line(path, 'OpenPLCModbusBridge/4', 'CommHealthy/1');
add_line(path, 'OpenPLCModbusBridge/5', 'Diagnostics/1');
end


function localAddCommandTags(modelName)
analogTags = { ...
    'PLC_P101A_SPEED', 'PLC_P101B_SPEED', 'PLC_P201_SPEED', ...
    'PLC_P301A_SPEED', 'PLC_P301B_SPEED', 'PLC_DP201_OUTPUT'};
digitalTags = { ...
    'PLC_P101A_START', 'PLC_P101B_START', 'PLC_P201_START', ...
    'PLC_P301A_START', 'PLC_P301B_START', 'PLC_M201_START', ...
    'PLC_XV201_OPEN'};
faultTags = { ...
    'FAULT_P301A_TRIP', 'FAULT_AIT201_FREEZE', ...
    'FAULT_XV201_STUCK_CLOSED', 'FAULT_COMMS_LOSS'};

for k = 1:numel(analogTags)
    blockName = ['Goto_' analogTags{k}];
    y = 50 + (k-1)*38;
    add_block('simulink/Signal Routing/Goto', ...
        [modelName '/' blockName], ...
        'GotoTag', analogTags{k}, ...
        'Position', [2540 y 2705 y+20]);
    add_line(modelName, sprintf('OpenPLC_Analog_Demux/%d', k), ...
        [blockName '/1'], 'autorouting', 'on');
end

for k = 1:numel(digitalTags)
    blockName = ['Goto_' digitalTags{k}];
    y = 285 + (k-1)*38;
    add_block('simulink/Signal Routing/Goto', ...
        [modelName '/' blockName], ...
        'GotoTag', digitalTags{k}, ...
        'Position', [2745 y 2925 y+20]);
    add_line(modelName, sprintf('OpenPLC_Digital_Demux/%d', k), ...
        [blockName '/1'], 'autorouting', 'on');
end

for k = 1:numel(faultTags)
    blockName = ['Goto_' faultTags{k}];
    y = 555 + (k-1)*38;
    add_block('simulink/Signal Routing/Goto', ...
        [modelName '/' blockName], ...
        'GotoTag', faultTags{k}, ...
        'Position', [2540 y 2745 y+20]);
    add_line(modelName, sprintf('OpenPLC_Fault_Demux/%d', k), ...
        [blockName '/1'], 'autorouting', 'on');
end
end


function localAddConditionedActuatorCommands(modelName)
% Each pump receives speed only when its matching PLC start coil is true.
localAddProductCommand(modelName, ...
    'PLC_P101A_Command', {'PLC_P101A_SPEED', 'PLC_P101A_START'}, ...
    [165 125 205 175], 'P101A_Actuator/1');
localAddProductCommand(modelName, ...
    'PLC_P101B_Command', {'PLC_P101B_SPEED', 'PLC_P101B_START'}, ...
    [165 190 205 240], 'P101B_Actuator/1');
localAddProductCommand(modelName, ...
    'PLC_P201_Command', {'PLC_P201_SPEED', 'PLC_P201_START'}, ...
    [565 480 605 530], 'P201_Actuator/1');
localAddProductCommand(modelName, ...
    'PLC_P301B_Command', {'PLC_P301B_SPEED', 'PLC_P301B_START'}, ...
    [965 315 1005 365], 'P301B_Actuator/1');

% A P-301A trip and an XV-201 stuck-closed injection must also affect the
% simulated physical devices, not only the PLC alarm logic.
localAddNotFromTag(modelName, ...
    'FAULT_P301A_TRIP', 'P301A_NotTripped', [860 175 900 205]);
localAddProductCommand(modelName, ...
    'PLC_P301A_Command', ...
    {'PLC_P301A_SPEED', 'PLC_P301A_START', 'P301A_NotTripped/1'}, ...
    [965 165 1005 225], 'P301A_Actuator/1');

localAddNotFromTag(modelName, ...
    'FAULT_XV201_STUCK_CLOSED', 'XV201_NotStuck', [560 650 600 680]);
localAddProductCommand(modelName, ...
    'PLC_XV201_Command', {'PLC_XV201_OPEN', 'XV201_NotStuck/1'}, ...
    [650 650 690 700], 'XV201_Valve/1');

% Dosing output and mixer command do not need an additional start gate.
localAddFromTag(modelName, 'PLC_DP201_OUTPUT', ...
    'From_PLC_DP201_OUTPUT', [565 355 705 375]);
localDisconnectInput(modelName, 'Treatment_Concentration/1');
add_line(modelName, 'From_PLC_DP201_OUTPUT/1', ...
    'Treatment_Concentration/1', 'autorouting', 'on');

localAddFromTag(modelName, 'PLC_M201_START', ...
    'From_PLC_M201_START', [565 405 705 425]);
localDisconnectInput(modelName, 'Treatment_Concentration/2');
add_line(modelName, 'From_PLC_M201_START/1', ...
    'Treatment_Concentration/2', 'autorouting', 'on');
end


function localAddProductCommand(modelName, blockName, inputs, position, destination)
productPath = [modelName '/' blockName];
add_block('simulink/Math Operations/Product', productPath, ...
    'Inputs', repmat('*', 1, numel(inputs)), ...
    'Position', position);

for k = 1:numel(inputs)
    source = inputs{k};
    if contains(source, '/')
        sourcePort = source;
    else
        fromName = sprintf('From_%s_%s', blockName, source);
        localAddFromTag(modelName, source, fromName, ...
            [position(1)-145, position(2)+(k-1)*25, ...
             position(1)-20, position(2)+20+(k-1)*25]);
        sourcePort = [fromName '/1'];
    end
    add_line(modelName, sourcePort, ...
        sprintf('%s/%d', blockName, k), 'autorouting', 'on');
end
% Deleting a source block can leave its old signal line connected to the
% destination port. Remove that line explicitly before installing the PLC
% command so this builder works consistently across Simulink releases.
localDisconnectInput(modelName, destination);
add_line(modelName, [blockName '/1'], destination, 'autorouting', 'on');
end


function localDisconnectInput(modelName, destination)
separator = find(destination == '/', 1, 'last');
assert(~isempty(separator), ...
    'Destination must use the form BlockName/InputPortNumber.');

blockName = destination(1:separator-1);
portNumber = str2double(destination(separator+1:end));
assert(isfinite(portNumber) && portNumber >= 1 && portNumber == fix(portNumber), ...
    'Destination input port number must be a positive integer.');

lineHandles = get_param([modelName '/' blockName], 'LineHandles');
assert(portNumber <= numel(lineHandles.Inport), ...
    'Destination input port does not exist: %s/%s', modelName, destination);

lineHandle = lineHandles.Inport(portNumber);
if lineHandle ~= -1
    delete_line(lineHandle);
end
end


function localAddNotFromTag(modelName, tagName, blockName, position)
fromName = ['From_' tagName];
localAddFromTag(modelName, tagName, fromName, ...
    [position(1)-165 position(2) position(1)-35 position(4)]);
add_block('simulink/Logic and Bit Operations/Logical Operator', ...
    [modelName '/' blockName], ...
    'Operator', 'NOT', ...
    'Position', position);
add_line(modelName, [fromName '/1'], [blockName '/1']);
end


function localAddFromTag(modelName, tagName, blockName, position)
add_block('simulink/Signal Routing/From', ...
    [modelName '/' blockName], ...
    'GotoTag', tagName, ...
    'Position', position);
end


function localAddIntegrationLogging(modelName)
add_block('simulink/Sinks/To Workspace', ...
    [modelName '/Log_OpenPLC_Measurements'], ...
    'VariableName', 'sim_OpenPLC_Measurements', ...
    'SaveFormat', 'Timeseries', ...
    'MaxDataPoints', 'inf', ...
    'Position', [2115 455 2315 480]);
add_block('simulink/Sinks/To Workspace', ...
    [modelName '/Log_OpenPLC_Feedback'], ...
    'VariableName', 'sim_OpenPLC_Feedback', ...
    'SaveFormat', 'Timeseries', ...
    'MaxDataPoints', 'inf', ...
    'Position', [2115 485 2315 510]);
add_block('simulink/Sinks/To Workspace', ...
    [modelName '/Log_OpenPLC_AnalogCommands'], ...
    'VariableName', 'sim_OpenPLC_AnalogCommands', ...
    'SaveFormat', 'Timeseries', ...
    'MaxDataPoints', 'inf', ...
    'Position', [2115 530 2315 555]);
add_block('simulink/Sinks/To Workspace', ...
    [modelName '/Log_OpenPLC_DigitalCommands'], ...
    'VariableName', 'sim_OpenPLC_DigitalCommands', ...
    'SaveFormat', 'Timeseries', ...
    'MaxDataPoints', 'inf', ...
    'Position', [2115 575 2315 600]);
add_block('simulink/Sinks/To Workspace', ...
    [modelName '/Log_OpenPLC_FaultInputs'], ...
    'VariableName', 'sim_OpenPLC_FaultInputs', ...
    'SaveFormat', 'Timeseries', ...
    'MaxDataPoints', 'inf', ...
    'Position', [2115 620 2315 645]);
add_block('simulink/Sinks/To Workspace', ...
    [modelName '/Log_OpenPLC_CommHealthy'], ...
    'VariableName', 'sim_OpenPLC_CommHealthy', ...
    'SaveFormat', 'Timeseries', ...
    'MaxDataPoints', 'inf', ...
    'Position', [2115 665 2315 690]);
add_block('simulink/Sinks/To Workspace', ...
    [modelName '/Log_OpenPLC_Diagnostics'], ...
    'VariableName', 'sim_OpenPLC_Diagnostics', ...
    'SaveFormat', 'Timeseries', ...
    'MaxDataPoints', 'inf', ...
    'Position', [2115 710 2315 735]);

add_line(modelName, 'OpenPLC_Measurements/1', ...
    'Log_OpenPLC_Measurements/1', 'autorouting', 'on');
add_line(modelName, 'OpenPLC_Feedback/1', ...
    'Log_OpenPLC_Feedback/1', 'autorouting', 'on');
add_line(modelName, 'OpenPLC_Communication/1', ...
    'Log_OpenPLC_AnalogCommands/1', 'autorouting', 'on');
add_line(modelName, 'OpenPLC_Communication/2', ...
    'Log_OpenPLC_DigitalCommands/1', 'autorouting', 'on');
add_line(modelName, 'OpenPLC_Communication/3', ...
    'Log_OpenPLC_FaultInputs/1', 'autorouting', 'on');
add_line(modelName, 'OpenPLC_Communication/4', ...
    'Log_OpenPLC_CommHealthy/1', 'autorouting', 'on');
add_line(modelName, 'OpenPLC_Communication/5', ...
    'Log_OpenPLC_Diagnostics/1', 'autorouting', 'on');
end


function localDeleteBlock(path)
if getSimulinkBlockHandle(path) ~= -1
    delete_block(path);
end
end


function localCloseModel(modelName)
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
end
